__name__ = 'djangoadminreports'
__description__ = 'Reports for django-admin'
__url__ = 'https://github.com/sunscrapers/django-admin-reports'
__version__ = '0.11.0'
__build__ = 0x001100
__author__ = 'Piotr Szpetkowski'
__author_email__ = 'piotr.szpetkowski@pyquest.space'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2017 Piotr Szpetkowski'